name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm install
        # Points for installing CI/CD toolchain/dependencies

      # Formatting
      - name: Run code formatter
        run: npm run format
        # Points for formatting

      # Linting
      - name: Run linter
        run: npm run lint
        # Points for linting

      # Run unit tests
      - name: Run unit tests
        run: npm test
        # Points for running unit tests

      # Optional: Lint Dockerfile using a script
      - name: Set up hadolint
        run: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.6.0/hadolint-Linux-x86_64
          chmod +x /bin/hadolint

      - name: Lint Dockerfile
        run: hadolint Dockerfile
        # Points for optional Dockerfile linting

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-image-name .
        # Points for building the Docker image

      # Push Docker image to registry
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push my-image-name
        # Points for pushing the Docker image
