name: github-action

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
    
jobs:
  cicd:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check for formatting issues
        run: |
          git diff --exit-code
        continue-on-error: false

      - name: Lint backend code
        uses: wearerequired/lint-action@v2
     
      - name: Run tests
        run: |
          PYTHONPATH=. pytest test.py --disable-pytest-warnings -v
      
      - name: Build Docker image
        uses: docker/setup-buildx-action@v3


